import{ChangeDetectionStrategy,ChangeDetectorRef,Component,OnDestroy,OnInit,ViewChild}from '@angular/core';import{BrowserModule}from '@angular/platform-browser';import{Columns,Config,DefaultConfig}from 'ngx-easy-table';import{NgModule,CUSTOM_ELEMENTS_SCHEMA}from '@angular/core';import{interval,Observable,Subject,timer}from 'rxjs';import{map,takeUntil}from 'rxjs/operators';import{HomeComponent}from './home/home.component';import{PancakeService,pancakePairPrice1,pancakePairPrice2,pancakePairPrice3,pancakeTokenMap}from './providers/pancake.service';import{ApeService,apeTokenMap}from './providers/ape.service';import{BakeryService,bakeryPairPrice1,bakeryPairPrice2,bakeryPairPrice3,bakeryTokenMap}from './providers/bakery.service';import{data1 as _data1,data2 as _data2,columns as _columns}from './constants/data/table_data';import{JsonEncoderService,jsonStr}from './workers/json-encoder.service';import{NgxDatatableModule,ColumnMode}from '@swimlane/ngx-datatable';import{NgxChartsModule,ViewDimensions,BaseChartComponent,colorSets}from '@swimlane/ngx-charts';import{multi}from './data';import{LatteService}from './providers/latte.service';import{BiswapService}from './providers/biswap.service';import{ApeSwapService}from './services/ape-swap.service';export var colorScheme={color:['#5AA454','#E44D25','#CFC0BB','#7aa3e5','#a8385d','#aae3f5']};export var columns2=[{prop:'name',name:'Name'},{name:'Gender'}];export let arbentina:string;interface Data{status:string;amount:number;company:string;limit:number;balance:number}
@Component({selector:'app-root',templateUrl:'./app.component.html',styleUrls:['./app.component.css'],changeDetection:ChangeDetectionStrategy.OnPush})export class AppComponent{title(title:any){throw new Error('Method not implemented.')}
@ViewChild('mydatatable')mydatatable:any;multi:any[]=[];view:[number,number]=[700,300];ColumnMode=ColumnMode;rows1=[{exchange:'arbentinaswap',token:'arbentina gold',value:'.00001'}];rows2=[{name:'Callie',gender:'Female'}];columns1=[{prop:'exchange'},{name:'token'},{name:'value'}];constructor(private cd:ChangeDetectorRef,private cdr:ChangeDetectorRef,public cake:PancakeService,public bake:BakeryService,public ape:ApeService,public latte:LatteService,public biswap:BiswapService,public jsonEncoderServer:JsonEncoderService){Object.assign(this,{multi})}
ops:number=7;source=timer(100,1000).subscribe(async(x)=>{switch(this.ops){case 0:arbentina="wbnb";this.cake.conventionSwitch(arbentina);this.bake.conventionSwitch(arbentina);this.ape.conventionSwitch(arbentina);this.rows1[0]={exchange:'pancake',token:"wbnb",value:pancakeTokenMap.wbnb.toString()}
this.rows1[1]={exchange:'bakery',token:"wbnb",value:bakeryTokenMap.wbnb.toString()}
this.rows1[2]={exchange:'ape',token:"wbnb",value:apeTokenMap.wbnb.toString()}
this.ops=7;this.rows1=[...this.rows1];break;case 1:arbentina="shiba";this.cake.conventionSwitch(arbentina);this.rows1[3]={exchange:'pancake',token:"shiba",value:pancakeTokenMap.shiba.toString()}
this.bake.conventionSwitch(arbentina);this.rows1[4]={exchange:'bakery',token:"shiba",value:bakeryTokenMap.shiba.toString()}
this.ape.conventionSwitch(arbentina);this.rows1[5]={exchange:'ape',token:"shiba",value:apeTokenMap.shiba.toString()}
this.ops=2;this.rows1=[...this.rows1];break;case 2:arbentina="eth";this.cake.conventionSwitch(arbentina);this.rows1[6]={exchange:'pancake',token:arbentina,value:pancakeTokenMap[arbentina].toString()}
this.bake.conventionSwitch(arbentina);this.rows1[7]={exchange:'bakery',token:arbentina,value:bakeryTokenMap[arbentina].toString()}
this.ape.conventionSwitch(arbentina);this.rows1[8]={exchange:'ape',token:arbentina,value:apeTokenMap[arbentina].toString()}
this.ops=4;this.rows1=[...this.rows1];break;case 4:arbentina="alpaca";this.latte.conventionSwitch(arbentina);break;case 5:arbentina='biswap';this.biswap.conventionSwitch(arbentina);break;case 7:arbentina='eth';this.cake.conventionSwitch(arbentina);break;default:console.log("Invalid operator")}
this.rows1.push();this.cd.markForCheck();this.jsonEncoderServer.objLit()})}
